version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: shenoda/php_mvc
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_mvc
      MYSQL_USER: php_mvc
      MYSQL_PASSWORD: php_mvc